### PR TITLE
addedBootstrap

### PR DESCRIPTION
**Pull request by AchiangahF**
yoo boy i have added boostrap to the node modules folder and i imported it into the project in the index.js file

### CODE REVIEW

**Comment by kongnyuroger** [comment]
confirm. Ihave seen it

**Comment by kongnyuroger** [comment]
I am locking for a way to open the code here and review it . but am not seing

**Comment by kongnyuroger** [comment]
i want to review the code before merging. just for good practice

**Comment by AchiangahF** [comment]
Ahh in the navigation up go to change files

**Comment by AchiangahF** [comment]
yoo boy please for the pictures for the work page

**Pull request merged**
